### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by AminaLEM** [adbailey4/yeast_rrna_modification_detection#3]
Hello @adbailey4 

I get the following error when I run the minimal example with the docker image:

Running SignalAlign
Traceback (most recent call last):
  File "/opt/venv/bin/inference_pipeline.py", line 232, in <module>
    ret, time = (time_it(main))
  File "/opt/venv/lib/python3.7/site-packages/py3helpers/utils.py", line 169, in time_it
    something = func(*args)
  File "/opt/venv/bin/inference_pipeline.py", line 218, in main
    threads=args.threads)
  File "/opt/venv/bin/inference_pipeline.py", line 143, in create_config
    urllib.request.urlretrieve(os.path.join(head_node, x), os.path.join(outpath, x))
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

It seems that the trained model ("https://bailey-k8s.s3-us-west-2.amazonaws.com/yeast_models") is not accessible. 

Thanks, 

Amina

**Comment by adbailey4** [comment]
Ah, ok this is a good catch. I think I migrated those models elsewhere after I graduated but forgot to update the Docker file. I will fix it sometime next week.

**Comment by adbailey4** [comment]
@AminaLEM Ok, I updated the Docker image. Can you try pulling the new image and running the same command?

**Comment by AminaLEM** [comment]
Thank you very much  @adbailey4 , I used docker again. The problem of the training model is fixed but another problem is raising something related to multithread package:

Traceback (most recent call last):
  File "/opt/venv/bin/runSignalAlign.py", line 12, in <module>
    from signalalign.filter_reads import filter_reads, filter_reads_to_string_wrapper
  File "/opt/venv/lib/python3.7/site-packages/signalalign/filter_reads.py", line 20, in <module>
    from signalalign.utils import multithread
  File "/opt/venv/lib/python3.7/site-packages/signalalign/utils/multithread.py", line 4, in <module>
    from pathos.multiprocessing import ProcessingPool as Pool
  File "/opt/venv/lib/python3.7/site-packages/pathos/__init__.py", line 48, in <module>
    from . import pools
  File "/opt/venv/lib/python3.7/site-packages/pathos/pools.py", line 12, in <module>
    from pathos.helpers import ProcessPool as _ProcessPool
  File "/opt/venv/lib/python3.7/site-packages/pathos/helpers/__init__.py", line 10, in <module>
    from . import pp_helper
  File "/opt/venv/lib/python3.7/site-packages/pathos/helpers/pp_helper.py", line 30, in <module>
    from pp import _Task
ImportError: cannot import name '_Task' from 'pp' (/opt/venv/lib/python3.7/site-packages/pp/__init__.py)
Traceback (most recent call last):
  File "/opt/venv/bin/inference_pipeline.py", line 232, in <module>
    ret, time = (time_it(main))
  File "/opt/venv/lib/python3.7/site-packages/py3helpers/utils.py", line 169, in time_it
    something = func(*args)
  File "/opt/venv/bin/inference_pipeline.py", line 222, in main
    check_call(f"runSignalAlign.py run --config {config_path}".split())
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['runSignalAlign.py', 'run', '--config', '/data/signalalign_output/sa_run_config.json']' returned non-zero exit status 1.

**Comment by adbailey4** [comment]
Alright, I just updated some stuff to fix that issue. Try pulling the latest docker image and let me know what happens!

**Comment by adbailey4** [comment]
I just re-ran the commands from [here](https://github.com/adbailey4/yeast_rrna_modification_detection#minimal-example) and everything finished as expected. Closing issue for now
